# run with: $ docker-compose down && docker-compose up >server.log

version: '3'
services:

  mongo:
    image: mongo:4.2@sha256:1c2243a5e21884ffa532ca9d20c221b170d7b40774c235619f98e2f6eaec520a
    command: mongod --port 27017 --quiet --nojournal
    # volumes:
    #   - /data
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: none

  web:
    depends_on:
      - mongo
    image: node:12
    user: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    environment:
      - JWT_KEY=secret
      - PORT=3000
      - MONGODB_URI="mongodb://mongo:27017/notes-api"
      # - MONGODB_URI="mongodb://root:example@mongo:27017"
      # - DB_NAME="notes-api"
